#!/bin/bash
DATAGEN_DIRNAME=${PARCEL_DIRNAME:-"DATAGEN-0.1.1-7.1.7.1000"}
export DATAGEN_JAR_PATH=${PARCELS_ROOT}/${DATAGEN_DIRNAME}/DATAGEN-0.2.0-7.1.7.1000.jar
export DATAGEN_MODELS_DIR=${PARCELS_ROOT}/${DATAGEN_DIRNAME}/models/
export DATAGEN_DICO_DIR=${PARCELS_ROOT}/${DATAGEN_DIRNAME}/dictionaries/
export DATAGEN_PROPERTIES_FILE=${PARCELS_ROOT}/${DATAGEN_DIRNAME}/application.properties
export DATAGEN_LOG_CONF_FILE=${PARCELS_ROOT}/${DATAGEN_DIRNAME}/logback.xml