---
##############################################
############# Launch DATAGEN #############

- name: Launch Datagen
  hosts: edge
  gather_facts: false
  roles: 
    - auto_configure/cm-config
    - launch_datagen/add_service
    - launch_datagen/launch_command