---
- name: Copy CSD to CM
  copy:
    src: "/tmp/{{ dg_name }}.jar"
    dest: "/opt/cloudera/csd/{{ dg_name }}.jar"

- name: Restart CM 
  systemd:
    state: restarted
    name: cloudera-scm-server

# TODO: make sure CM is restarted
- name: Wait 1 minute to make sure CM is restarted
  pause:
    seconds: 60